### ISSUE TITLE
Unable to add profile at all

### ISSUE THREAD

**Issue by andrewzagorski** [algolia/cli#104]
I just installed the algolia CLI via homebrew for MacOS (MacOS version 12.6.1, homebrew 3.6.19, algolia version 1.2.1). When running `algolia profile add` with credentials copied from my dashboard, the command fails with the error message, `invalid application credentials`. The credentials are valid, it's what I use in production. Adding the credentials as flags to the command does not work either.

I tried regenerating my admin API key to no avail. Has anyone else encountered this issue?

**Comment by khalidelassaad** [comment]
Hi Andrew!

Just as a sanity check in case your copy/paste operation is somehow missing a character or adding a special character, would you mind retrying by carefully manually entering your App ID and API key?

**Comment by andrewzagorski** [comment]
Yep.. that'll do it. In that case, I'd hope they fix the dashboard to not copy any special characters to your clipboard!

**Comment by andrewzagorski** [comment]
I copied both the application ID as well as the api key from the "API Keys" part of the settings menus, using the "copy to clipboard" buttons.

Chrome: Version 108.0.5359.124
MacOs 12.6.1
Terminal app-zsh

**Comment by tonlam** [comment]
I have the same issue
