### ISSUE TITLE
invalid application credentials

### ISSUE THREAD

**Issue by DanRoscigno** [algolia/cli#114]
Hi Folks,
I am trying to setup the cli.  When I run `algolia profile add` I get asked for the name, application ID, and admin API key.  I cannot find an "admin API key" on my dashboard.  Is it called something else?  I tried all of the API keys, even the one for the crawler.  I get "invalid application credentials" with all of them.

Thanks!

**Comment by gregfenton** [comment]
The "admin API key" is inside your application's dashboard:
> ![image](https://github.com/algolia/cli/assets/4407559/0a0bc486-0258-4ad6-ab62-c1b2adb7c3b4)

and then:
> ![image](https://github.com/algolia/cli/assets/4407559/3acc6db4-32e4-4a0a-b68a-3119cd67ca1c)

**Comment by DanRoscigno** [comment]
Thanks @gregfenton
