### ISSUE TITLE
Profile added using Algolia CLI version 1.6.1 breaks `algolia profile list` command

### ISSUE THREAD

**Issue by risk1996** [algolia/cli#146]
### How to reproduce
1. Install `algolia` CLI version 1.6.1
2. Remove any existing profile
3. Add a new admin profile (using Admin API Key) using the installed version using the command `algolia profile add`
4. Run `algolia profile list`

### Actual
CLI reports 403 error
```
❯ algolia profile list 
Fetching configured profiles ⡿Algolia API error [403] Invalid Application-ID or API key
```

### Expected
Command `algolia profile list` works properly:
```
❯ algolia profile list
NAME      APPLICATION ID  NUMBER OF INDICES  DEFAULT
........  ..........      ..                 ✓
```

### Known previous working version
Tested adding the profile using version 1.5.0 and the `algolia profile list` works as expected

### Environment
OS: macOS 14.3.1 23D60 arm64
Shell: zsh 5.9
Terminal: iTerm2
Installation Method: Homebrew (`brew install algolia/algolia-cli/algolia`)

**Comment by clemfromspace** [comment]
@risk1996 Thank you for your detailed report! 

This should be fixed in the [1.6.2](https://github.com/algolia/cli/releases/tag/v1.6.2) release.
