### ISSUE TITLE
conflict with fig?

### ISSUE THREAD

**Issue by jeffrey-slentz-algolia** [algolia/cli#42]
Haven't used homebrew before so am not sure how to read or resolve this but it looks like I installed [FIG](https://github.com/aayoubi/figgen) first.
<img width="693" alt="image" src="https://user-images.githubusercontent.com/87393193/186772057-d9f4bcb0-9dbf-4e07-9b09-8bf0945366b4.png">

**Comment by khalidelassaad** [comment]
For whatever reason, it looks like `brew install algolia/algolia-cli` is resolving to two repos, one of which is the fig repo. Try `brew install algolia/algolia-cli/algolia`

**Comment by jeffrey-slentz-algolia** [comment]
This worked! Thanks!
