### ISSUE TITLE
error show : bufio.Scanner: token too long

### ISSUE THREAD

**Issue by kimi0230** [algolia/cli#55]
Hi~
When I run`algolia objects import index.zh-tw -F ./public/index.json`
It will show
`bufio.Scanner: token too long`

Algolia version 1.2.0
Is my index.json too large?  my index.json is 261 KB.

Thanks!!!

**Comment by clemfromspace** [comment]
@kimi0230 Thanks for opening an issue!

Juste to confirm, what is the format of the json files you are trying to upload?
The Algolia CLI only accept [json line separated](https://jsonlines.org/) files for now.

If that's the case (if you have only one object per line), we recently have a fix to allow bigger objects per line: #53
We will release a new version including the fix in the coming days.

**Comment by kimi0230** [comment]
> If that's the case (if you have only one object per line), we recently have a fix to allow bigger objects per line: #53 We will release a new version including the fix in the coming days.

Hi @clemfromspace 
It is works~
Thank you for your support.
